package:
  name: smartlibot
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/smartlichessbot/smartlibot.git

requirements:
  build:
    - python
    - setuptools
  run:    
    - PyYAML==3.12
    - requests==2.18.4
    - urllib3==1.22           
    - python-chess==0.23.5
    - backoff==1.5.0

test:
  imports:
    - smartlibot

about:
  home: https://github.com/smartlichessbot/smartlibot
  license: MIT
  license_file: LICENSE
